### PR TITLE
Fix notifications settings that were not remembered

### LINKED ISSUE #72: "Enable Notifications" and "Summarize Notifications" state is lost when exiting the application
**Describe the bug**
In the "Active Deals" screen, the state of "Enable Notifications" and "Summarize Notifications" checkboxes is lost when exiting the application. When opening the app, it is always set to "Enable Notifications" checked and "Summarize Notifications" unchecked.

**To Reproduce**
1. Go to Active Deals screen
2. Uncheck "Enable Notifications" and check "Summarize Notifications"
3. Exit the application normally
4. Re-open the applicatiom
5. "Enable Notifications" is checked and "Summarize Notifications" is unchecked. It should have been the opposite:  "Enable Notifications" unchecked and "Summarize Notifications" is checked

**Expected behavior**
The application should remember the state of "Enable Notifications" and "Summarize Notifications", even after restarting the application. I assume most users (including myself) expect these settings to be remembered, especially when they want to disable notifications.

**Desktop :**
 - OS: Windows 10
 - Version: `1.0.0`

**Additional context**
I browsed the code and found out these 2 settings are saved in the 3commas slice, which is not saved on disk and hence re initialized at each startup. I see there is another slice, config that is saved on disk and seem more appropriate. I propose to move the settings from 3commas slice to config slice. I think that the settings should be independant of the profile: it could be confusing for a user with multiple profiles to see the state of the checkbox change depending on the profile.

I'm interested in taking care of this issue, if that's good for you !

### PR DESCRIPTION
**Pull request by petitcl**
Fixes #72 

- Rename `SyncToggles` component to `NotificationsSettings` to better reflect its purpose
- Save notifications settings in the config object. I didn't put it in the local storage because the settings need to be accessed from the renderer and from the main process. Because of this use, it didn't make sense to me to use the local storage.
- Fix a bug where you would get a lot of old notifications when mixing between auto sync and full sync. I personally had this bug many times because I play with the buttons a lot. To reproduce on the main branch: start auto sync, wait for a tick, then trigger a full sync, and wait for another auto sync tick. That last tick will notify each deal closed since the beginning of the history (it should notify only if there were new deals closed since the full sync). I fixed it by not resetting the time to 0 after a full sync.

### CODE REVIEW

**Comment by coltoneshaw** [comment]
This is fantastic, thanks for all the hard work! Love the idea of storing this in the config file, makes a lot of sense honestly. 

My only thought here might be to pull the sync settings from the redux store and pass into the sync settings. Since we already have the data stored within redux.

**Comment by coltoneshaw** [comment]
Only other thing here is to write a config migration script to add this to the users config.json file. I'm more than happy to do that if you want since electron-store can be weird to work with.

**Comment by petitcl** [comment]
For the migration script, it's good for me if you take care of it. I'll take a look at how you do it so that I can get and idea of how it works.

For the sync settings point, I'm not really following, sorry. I thought we were already pulling the sync settings from the redux store. Could you give a bit more details ?

**Comment by coltoneshaw** [comment]
Just added some comments, let me know if it makes sense!

**Review by coltoneshaw — APPROVED** [review]

**Comment by coltoneshaw** [comment]
@petitcl - I did another review on this, sorry my prior comments seemed confusing. I pushed a few updates and actually still had the original issue. It seems when switching profiles we never reset the syncCount. Adjusted this, and added the config migration scripts we talked about.

Let me know if you have any feedback. I'll probably merge this here shortly.

**Comment by coltoneshaw** [comment]
@petitcl - I went ahead and merged this since I had to make some changes in the release branch that relied on this. Let me know if you noticed any issues and I'll open another PR to fix them. Thanks for this hard work!!

**Pull request merged**
